//// LocalHost User Endpoint ////
### GET all users
GET http://localhost:3000/user

### GET specific user
GET http://localhost:3000/user/67133ee10d1a562513baa581

### POST User
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
  "firstName": "TEST",
  "lastName": "TEST",
  "email": "na@na.com",
  "password": "$%&#asd333WagnerOnTheRun!",
  "savedDestinations": [],
  "photos": [],
  "reviews": []
}

### PUT edit user
PUT http://localhost:3000/user/67140e0aa6e6b0bacbb325d6 HTTP/1.1
Content-Type: application/json

{
  "gitHubId": "55414196",
  "username": "Bladedkiwi",
  "email": "bladedkiwi@byui.edu",
  "destinationPhotos": ["Here's a thing", "Here's a second thing"],
  "userPhotos": ["A photo object here", "And another"],
  "reviews": [],
  "__v": 0
}

### Delete User 
DELETE http://localhost:3000/user/67133ee10d1a562513baa581 HTTP/1.1 


//// LocalHost Review Endpoint ////
### GET all users
GET http://localhost:3000/review

### GET specific user
GET http://localhost:3000/review/67101478a437a62d1798bada

### POST User
POST http://localhost:3000/review HTTP/1.1
Content-Type: application/json

{
  "comments": "Good!",
  "stars": 4,
  "user": "670f03f4a437a62d1798ba87"
}

### PUT edit user
PUT http://localhost:3000/review/6713bc4eec0d1b2f6f2454db HTTP/1.1
Content-Type: application/json

{
  "comments": "Very Good!",
  "stars": 4,
  "user": "670f03f4a437a62d1798ba8a"
}

### Delete User 
DELETE http://localhost:3000/review/6713bc4eec0d1b2f6f2454db HTTP/1.1 


//// LocalHost Photo Endpoint ////
### GET all Photos
GET http://localhost:3000/photo

### GET specific Photo
GET http://localhost:3000/photo/6713bda5ec0d1b2f6f2454ed

### POST Photo
POST http://localhost:3000/photo HTTP/1.1
Content-Type: application/json

{
 "title": "My Cat",
  "imgUrl":"https://placecats.com/neo_banana/300/200",
  "imgAlt": "Two dogs named Neo and Banana",
  "description": "Photo of Neo and Banana such good boys"
}

### PUT edit user
PUT http://localhost:3000/photo/6713e1f549cfc8249e9c4aad HTTP/1.1
Content-Type: application/json

{
  "title": "My Cat",
  "imgUrl":"https://placecats.com/neo_banana/300/200",
  "imgAlt": "Two dogs named Neo and Banana",
  "description": "Photo of Neo and Banana such good boys"
}

### Delete User 
DELETE http://localhost:3000/photo/6713bd8bec0d1b2f6f2454ea HTTP/1.1 

//// LocalHost Destination Endpoint ////
### GET all destinations
GET http://localhost:3000/destination

### GET specific user
GET http://localhost:3000/destination/67100d69a437a62d1798bacf

### POST User
POST http://localhost:3000/destination HTTP/1.1
Content-Type: application/json

{
  "photo": [],
  "_id": "67100d69a437a62d1798bacf",
  "city": "Rome",
  "country": "Italy",
  "photos": [],
  "description": "The capital city of Italy, famous for its nearly 3,000 years of globally influential art, architecture, and culture.",
  "tourismSpots": [
    "Colosseum",
    "Vatican City",
    "Trevi Fountain"
  ],
  "reviews": []
}

### PUT edit user
PUT http://localhost:3000/destination/67133ee10d1a562513baa581 HTTP/1.1
Content-Type: application/json

{
  "photo": [],
  "_id": "67100d69a437a62d1798bacf",
  "city": "Rome",
  "country": "Italy",
  "photos": [],
  "description": "The capital city of Italy, famous for its nearly 3,000 years of globally influential art, architecture, and culture.",
  "tourismSpots": [
    "Colosseum",
    "Vatican City",
    "Trevi Fountain"
  ],
  "reviews": []
}

### Delete User 
DELETE http://localhost:3000/destination/67133ee10d1a562513baa581 HTTP/1.1 
